name: 部署到 xhioer.github.io
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装 Hexo
        run: npm install -g hexo-cli

      - name: 安装依赖
        run: npm install

      - name: 生成静态网站
        run: hexo clean && hexo generate

      - name: 发布到主站
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          external_repository: xhioer/xhioer.github.io
          publish_branch: gh-pages
